name: Public Npm

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish pnpm"

    environment: npm

    steps:
      - uses: actions/checkout@main

      - name: Install and Build
        run: |
          npm install
          npm run build # 这是我的项目的打包命令，你也可以改成你的

      - name: "Publish to the npm registry"
        run: |
          npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致
        with:
          default_branch: "main"
